version: '3.3'
services:
  ### Gateway ###
  gateway:
    depends_on:
      - db
    build: gateway
    ports:
      - 8080:8080
    volumes:
      - ./gateway:/app

  ## SmartSPEC service ###
  smartspec-service:
    build: smartspec-service
    depends_on:
      - db

    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: simcattle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./smartspec-service:/app

  ### Configuration service ###
  configuration-service:
    build: configuration-service
    depends_on:
      - db

    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: simcattle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./configuration-service:/app

  ### Location service ###
  location-service:
    build: location-service
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: simcattle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./location-service:/app

  ### Database ###
  db:
    image: mysql:8
    restart: always
    container_name: code-db
    command:
      - '--secure-file-priv='
    environment:
      MYSQL_DATABASE: simcattle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      # Where the data is persisted
      - my-db:/var/lib/mysql
      # Init scripts

      #mounts the ./data directory on the host system to the /data directory in the container. This is used to provide additional data files to the container.
      - ./data:/data

      #mounts the create_tables.sql file on the host system to the /docker-entrypoint-initdb.d/1.sql file in the container. This file is executed when the container is started, and is used to create the necessary database tables.
      # - ./scripts/init/grant_rights_to_user.sql:/docker-entrypoint-initdb.d/1.sql
      # - ./scripts/init/create_tables_final.sql:/docker-entrypoint-initdb.d/2.sql
      # - ./scripts/init/insert_in_smartspec_conf_final.sql:/docker-entrypoint-initdb.d/3.sql
      # # - ./scripts/init/insert_in_smartspec_conf_final_noevents.sql:/docker-entrypoint-initdb.d/3.sql
      # - ./scripts/init/load_data_from_csv_final.sql:/docker-entrypoint-initdb.d/4.sql
      # - ./scripts/init/transform_measurements_final.sql:/docker-entrypoint-initdb.d/5.sql
      
      - ./scripts/init/grant_rights_to_user.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/init/create_tables.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/init/insert_in_smartspec_conf.sql:/docker-entrypoint-initdb.d/3.sql
      - ./scripts/init/load_data_from_csv.sql:/docker-entrypoint-initdb.d/4.sql
  # ### Web UI ###
  web-ui:
    build: web-ui
    depends_on:
      - db
    environment:
      # REACT_APP_SERVER_URL: http://localhost:8080
      REACT_APP_SERVER_URL: http://157.230.24.1:8080

    volumes:
      - ./web-ui:/app

  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app

    volumes:
      - type: bind
        source: ./frontend/
        target: /srv/app
    tty: true

volumes:
  my-db: